//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HadithSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTEUR
    {
        public int ID_AUTEUR { get; set; }
        public string NOM_AUTEUR { get; set; }
        public string DATE_AUTEUR { get; set; }
        public string BIOGRAPHIE_AUTEUR { get; set; }
    }
}
