//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HadithSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAPITRE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHAPITRE()
        {
            this.HADITH = new HashSet<HADITH>();
        }
    
        public int ID_CHAPITRE { get; set; }
        public Nullable<int> NUMERO_CHAPITRE { get; set; }
        public string TITRE_CHAPITRE { get; set; }
        public Nullable<int> HADITH_CHAPITRE { get; set; }
        public Nullable<int> RECUEIL_CHAPITRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HADITH> HADITH { get; set; }
        public virtual HADITH HADITH1 { get; set; }
        public virtual RECUEIL RECUEIL { get; set; }
    }
}
