//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HadithSearch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_HADITHSEARCHEntities : DbContext
    {
        public DB_HADITHSEARCHEntities()
            : base("name=DB_HADITHSEARCHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTEUR> AUTEUR { get; set; }
        public virtual DbSet<AUTHENTICITE> AUTHENTICITE { get; set; }
        public virtual DbSet<CHAPITRE> CHAPITRE { get; set; }
        public virtual DbSet<HADITH> HADITH { get; set; }
        public virtual DbSet<RECUEIL> RECUEIL { get; set; }
        public virtual DbSet<TRANSMETTEUR> TRANSMETTEUR { get; set; }
    }
}
