//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HadithSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HADITH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HADITH()
        {
            this.CHAPITRE1 = new HashSet<CHAPITRE>();
        }
    
        public int ID_HADITH { get; set; }
        public Nullable<int> NUMERO_HADITH { get; set; }
        public Nullable<int> TRANSMETTEUR_HADITH { get; set; }
        public string TEXTE_HADITH { get; set; }
        public Nullable<int> AUTHENTICITE_HADITH { get; set; }
        public string COMMENTAIRE_HADITH { get; set; }
        public Nullable<int> CHAPITRE_HADITH { get; set; }
        public Nullable<int> RECUEIL_HADITH { get; set; }
    
        public virtual AUTHENTICITE AUTHENTICITE { get; set; }
        public virtual CHAPITRE CHAPITRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAPITRE> CHAPITRE1 { get; set; }
        public virtual RECUEIL RECUEIL { get; set; }
        public virtual TRANSMETTEUR TRANSMETTEUR { get; set; }
    }
}
