//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HadithSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECUEIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECUEIL()
        {
            this.CHAPITRE = new HashSet<CHAPITRE>();
            this.HADITH = new HashSet<HADITH>();
        }
    
        public int ID_RECUEIL { get; set; }
        public string TITRE_RECUEIL { get; set; }
        public Nullable<int> AUTEUR_RECUEIL { get; set; }
        public Nullable<int> CHAPITRE_RECUEIL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAPITRE> CHAPITRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HADITH> HADITH { get; set; }
    }
}
